# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'gitbookreader' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gitbookreader
  
  pod 'SSZipArchive',  '~> 1.8'

  target 'gitbookreader-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'gitbookreaderTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
